// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awnqffyjlelpaflfcwby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3bnFmZnlqbGVscGFmbGZjd2J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzQxMzIsImV4cCI6MjA3Mzg1MDEzMn0.wW8u5KUmZwWH9lKgWSQdDJr91Yeim1wG6HxdsS92VJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});